### ISSUE TITLE
Documentation for diabox connectivity

### ISSUE THREAD

**Issue by raferg** [swissalpine/GARMIN-xDrip-Spike-Nightscout-Watchface#1]
In the documentation for the Diabox connectivity, when testing it says to refer to the xDrip+ test, but it refers to the same URL 'http://127.0.0.1:17580/sgv.json?count=12' shouldn't it be unique for diabox (as otherwise they are both using the same URL).

**Comment by swissalpine** [comment]
The Diabox app is largely based on the open source code of xDrip+. Therefore, the structure and function of the web service is so similar that the query URL is also the same.
Since the number range 192.xxx.xxx.xx always refers to internal services, this should not be a problem - unless Diabox and xDrip are installed in parallel on the same smartphone. However, I think this is very unlikely.
Since it is the same URL, my apps work with Diabox exactly when xDrip is selected in the settings.

**Comment by raferg** [comment]
Thanks for the clarification @swissalpine . 
FWIW I do run both Diablo’s and xDrip on the same phone which is why there is this issue.
