### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by zehnBE** [swissalpine/GARMIN-xDrip-Spike-Nightscout-Watchface#4]
On wifi it works fine.
On Mobile Data it shows only Error 502
All right are set to yes and in the Browser it works.
Xdrip only is set. I have try all delay settings.
Which setting are wrong?
Latest Version of all (earlier xdrip does also not working.
Can you help?
Thx
Martin

**Comment by swissalpine** [comment]
That it works with WIFI when xDrip is selected as setting is actually not possible ...
As soon as xDrip is selected as source, an internal URL is called, which is not accessible via WiFi.
Also, the error code -502 is not documented at Garmin (cf. https://developer.garmin.com/connect-iq/api-docs/Toybox/Communications.html).
From therefore I am somewhat in the dark.

Regardless: In xDrip, the Web Service is enabled and the Open Web Service is disabled?

**Comment by zehnBE** [comment]
Yes, xdrip web Service ist enabled and open web Service is disabled.

**Comment by zehnBE** [comment]
Garmin watchface:
![Screenshot_2023-03-23-11-25-45-219_com garmin connectiq](https://user-images.githubusercontent.com/40665283/227175231-244dbc3f-df48-4c1d-ada3-5fc1b680808f.jpg)
![Screenshot_2023-03-23-11-25-53-822_com garmin connectiq](https://user-images.githubusercontent.com/40665283/227175251-ac743094-656c-43dc-981e-4f6546017029.jpg)

Xdrip:
![Screenshot_2023-03-23-11-27-07-108_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/40665283/227175595-0210ffda-68ff-4bd3-a510-025715ec1a5c.jpg)
Debuggen for Webservice is activated and works in wifi:
![Screenshot_2023-03-23-11-27-20-536_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/40665283/227175747-9354e6b6-97de-4d72-ae8b-4e0b38973eca.jpg)

If wifi disabled or out of range, no requests are loged in xdrip.

**Comment by zehnBE** [comment]
WiFi disabled:
![Uploading IMG_20230323_113209.jpg…]()

**Comment by zehnBE** [comment]
WiFi disabled:
![IMG_20230323_113209](https://user-images.githubusercontent.com/40665283/227177140-4c2e011b-297f-43d1-a5ac-83a54ee9475f.jpg)

**Comment by swissalpine** [comment]
WIFI must be disabled on some Garmin watches because the watchface must direct the web requests to Garmin Connect Mobile app. If WIFI is enabled it directs the request over WIFI network.
Is the Garmin Connect Mobile App running in the background (dontkillmyapp.com) and the bluetooth connection reliable?

**Comment by swissalpine** [comment]
If I read your screenshots correctly: It worked at 11:26 and fails 5 minutes later?
Do you see a log entry at 11:31? If there isn't any there was no comunnication between Garmin Mobile App and xDrip+.

**Comment by zehnBE** [comment]
Sorry for the delay!
When WiFi is on, i can see in xdrip Log the requests.
But not when WiFi is Off. There comes no requests in in the xdrip Log.
And all These Apps have all rights and can run complete time and are allowed to use mobile data.
Is there a debug Output on logcat from the watchface?

**Comment by swissalpine** [comment]
What I don't understand: it should be impossible for my Watchface to connect to xDrip via WIFI!
It asks for an internal IP of xDrip+, this can only be reached as follows:
Watch -- via Bluetooth --> Garmin Connect Mobile App -- internal connection --> http://127.0.0.1:17580/sgv.json?count=18 @ xDrip+
This IP should not be reachable via WLAN, the router doesn't even know where to route this address to!
A logcat there is not, everything happens on the watch. 
Also I never (!) see entries in xDrip+, I did not even know that xDrip+ logs the web service. Is there a trick to enable it?
If Garmin Connect Mobile App is not subject to any restrictions, even the Bluetooth apps are not terminated in the background, I really unfortunately have no idea what is going wrong with you.

Do you have other apps accessing the internal server of xDrip+?
Have you activated any firewall on your smartphone that blocks access?
Are you rooted and have an app blocker that uses internal addresses for redirects to nowhere?
If I take 502 seriously as a bad gateway error, it must be a communication problem between Garmin Connect Mobile and xDrip+ ...

Since I really don't know how to help you, I'm wondering if talking on the phone will do any good?

**Comment by swissalpine** [comment]
If you google error 502 and Garmin Connect, you will find issues with the amazon music app. Amazon has published a trouble shooting. Maybe there is something here that will help you?
https://images-eu.ssl-images-amazon.com/images/I/817GgcTP9TS.pdf

**Comment by swissalpine** [comment]
And one last thought: Could it be that you are using Juggluco and have the Juggluco web server turned on?
According to this post 
https://insulinclub.de/index.php?thread/34255-libre3-2-juggluco/&postID=686979#post686979
it responds to the same (!) web address as the xDrip+ web server ... (if I understood that correctly). This would of course also explain why the communication fails ...
